# Generated by Django 5.2.3 on 2025-07-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_admin_username"),
        ("orders", "0005_remove_order_guest_email_remove_order_guest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.address",
            ),
        ),
    ]
