# Generated by Django 5.2.3 on 2025-07-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_guestuser_alter_address_user_address_guest"),
        ("orders", "0006_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.guestuser",
            ),
        ),
    ]
